name: generate GitHub profile 3D contribution

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 1000

      - name: Commit and push generated files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add profile-3d-contrib
          git diff --cached --quiet && echo "No changes to commit" && exit 0
          git commit -m "chore: update 3d contributions"
          git push
